{{- if .Values.pvc }}
{{- range .Values.pvc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Added | quote for robustness
  name: {{ .name | quote }}
  # Best Practice: Add standard labels for your release
  labels:
    {{- include "mealie.labels" $ | nindent 4 }}
  # Best Practice: Explicitly define the namespace
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    # Corrected: The default value is now a string.
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      # Added | quote to ensure this is always a string, which is required.
      storage: {{ .size | quote }}
  {{- if .storageClass }}
  # Added | quote for robustness
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
